/OLA_project/
│── OLA_project.py
│── requirements.txt
│── .streamlit/
    └── secrets.toml

        [mysql]
        host = "localhost"
        port = "3306"
        user = "root"
        password = "PAra!1001"
        database = "ola_project"


