/OLA_project/
│── OLA_project.py
│── requirements.txt
│── .streamlit/
    └── secrets.toml

[mysql]
host = "your-db-host"        # e.g. "127.0.0.1" (local) or PlanetScale/Railway URL
user = "root"
password = "yourpassword"
database = "OLA_project"
